# frozen_string_literal: true

require 'maremma'

## Set a default host for urls generated by the DOI registrars (if necessary)
Rails.application.routes.default_url_options[:host] = 'localhost:3000'

## Remote identifiers configuration
# Add registrar implementations by uncommenting and adding to the hash below.
# See app/services/hyrax/identifier/registrar.rb for the registrar interface
Hyrax.config.identifier_registrars = { datacite: Hyrax::DOI::DataCiteRegistrar }

## For DataCite DOIs
# Test mode will use the DataCite test environment
Hyrax::DOI::DataCiteRegistrar.mode = :test # Possible options are [:production, :test]
Hyrax::DOI::DataCiteRegistrar.prefix = ENV['DATACITE_PREFIX']
Hyrax::DOI::DataCiteRegistrar.username = ENV['DATACITE_USERNAME']
Hyrax::DOI::DataCiteRegistrar.password = ENV['DATACITE_PASSWORD']

require_dependency Pathname.new(Gem.loaded_specs['bolognese'].full_gem_path).join('lib', 'bolognese', 'doi_utils').to_s

Bolognese::DoiUtils.module_eval do
  def doi_resolver(doi, options = {})
    sandbox = Array(/handle.stage.datacite.org/.match(doi)).last
    sandbox.present? || options[:sandbox] ? "https://handle.test.datacite.org/" : "https://doi.org/"
  end

  def doi_api_url(doi, options = {})
    sandbox = Array(/handle.stage.datacite.org/.match(doi)).last
    sandbox.present? || options[:sandbox] ? "https://api.test.datacite.org/dois/#{doi_from_url(doi)}?include=media,client"  : "https://api.datacite.org/dois/#{doi_from_url(doi)}?include=media,client"
  end
end

## Fix UTF8 encoding bug https://github.com/datacite/maremma/issues/17
Maremma.class_eval do
  def self.parse_response(string, options = {})
    string = string.dup
    string =
      if options[:skip_encoding]
        string
      else
        string.force_encoding('utf-8').encode(
          Encoding.find("UTF-8"),
          invalid: :replace,
          undef: :replace,
          replace: "?"
        )
      end
    return string if options[:raw]

    from_json(string) || from_xml(string) || from_string(string)
  end
end
