# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = CollectionIndexer
  after_update :remove_featured, if: proc { |collection| collection.private? }
  after_destroy :remove_featured

  def remove_featured
    FeaturedCollection.where(collection_id: id).destroy_all
  end
end
