replicaCount: 2

resources:
  requests:
    memory: "1Gi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

brandingVolume:
  storageClass: efs-sc
derivativesVolume:
  storageClass: efs-sc
uploadsVolume:
  storageClass: efs-sc
  size: 200Gi

extraVolumeMounts: &volMounts
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/imports
    subPath: imports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/exports
    subPath: exports
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/system
    subPath: public-system
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/public/uploads
    subPath: public-uploads
  - name: uploads
    mountPath: /app/samvera/hyrax-webapp/tmp/network_files
    subPath: network-files

ingress:
  enabled: true
  hosts:
    - host: oar.notch8.cloud
      paths:
        - path: /
    - host: "*.oar.notch8.cloud"
      paths:
        - path: /
  annotations:
    {
      kubernetes.io/ingress.class: "nginx",
      nginx.ingress.kubernetes.io/proxy-body-size: "0",
      cert-manager.io/cluster-issuer: letsencrypt-production-dns,
    }
  tls:
    - hosts:
        - oar.notch8.cloud
        - "*.oar.notch8.cloud"
      secretName: notch8cloud

extraEnvVars: &envVars
  - name: CONFDIR
    value: "/app/samvera/hyrax-webapp/solr/config"
  - name: DATABASE_ADAPTER
    value: postgresql
  - name: DATABASE_HOST
    value: postgresql.default.svc.cluster.local
  - name: DATABASE_NAME
    value: hyku
  - name: DATABASE_PASSWORD
    value: $DATABASE_PASSWORD
  - name: DATABASE_USER
    value: postgres
  - name: FCREPO_BASE_PATH
    value: /bl
  - name: FCREPO_HOST
    value: fcrepo.fcrepo.svc.cluster.local:8080
  - name: FCREPO_PATH
    value: /rest
  - name: FEDORA_URL
    value: http://fcrepo.fcrepo.svc.cluster.local:8080/rest
  - name: INITIAL_ADMIN_EMAIL
    value: support@notch8.com
  - name: INITIAL_ADMIN_PASSWORD
    value: testing123
  - name: IN_DOCKER
    value: "true"
  - name: LD_LIBRARY_PATH
    value: /app/fits/tools/mediainfo/linux
  - name: PASSENGER_APP_ENV
    value: production
  - name: RAILS_CACHE_STORE_URL
    value: redis://:production@hyku-production-redis-master:6379/bl
  - name: RAILS_ENV
    value: production
  - name: RAILS_LOG_TO_STDOUT
    value: "true"
  - name: RAILS_MAX_THREADS
    value: "5"
  - name: RAILS_SERVE_STATIC_FILES
    value: "true"
  - name: REDIS_HOST
    value: hyku-production-redis-master
  - name: REDIS_URL
    value: redis://:production@hyku-production-redis-master:6379/bl
  - name: HYRAX_ACTIVE_JOB_QUEUE
    value: sidekiq
  - name: HYKU_BULKRAX_ENABLED
    value: "true"
  - name: HYKU_CONTACT_EMAIL
    value: support@notch8.com
  - name: HYKU_FILE_ACL
    value: "false"
  - name: HYRAX_FITS_PATH
    value: /app/fits/fits.sh
  - name: HYKU_ADMIN_HOST
    value: admin.iro.bl.uk
  - name: HYKU_ADMIN_ONLY_TENANT_CREATION
    value: "true"
  - name: HYKU_ALLOW_SIGNUP
    value: "false"
  - name: HYKU_DEFAULT_HOST
    value: "%{tenant}.iro.bl.uk"
  - name: HYKU_MULTITENANT
    value: "true"
  - name: HYKU_ROOT_HOST
    value: iro.bl.uk
  - name: HYKU_SMTP_SETTINGS
    value: '{"from":"openaccess@bl.uk","user_name":"apikey","password":"$SMTP_PASSWORD","address":"smtp.sendgrid.net","domain":"bl.uk","port":"587","authentication":"plain","enable_starttls_auto":true}'
  - name: SMTP_ADDRESS
    value: smtp.sendgrid.net
  - name: SMTP_DOMAIN
    value: "bl.uk"
  - name: SMTP_ENABLED
    value: "true"
  - name: SMTP_PASSWORD
    value: $SMTP_PASSWORD
  - name: SMTP_PORT
    value: "587"
  - name: SMTP_USER_NAME
    value: apikey
  - name: SMTP_TYPE
    value: plain
  - name: SOLR_ADMIN_USER
    value: admin
  - name: SOLR_COLLECTION_NAME
    value: hyku
  - name: SOLR_CONFIGSET_NAME
    value: hyku
  - name: SOLR_HOST
    value: solr.default.svc.cluster.local
  - name: SOLR_PORT
    value: "8983"
  - name: SOLR_ADMIN_PASSWORD
    value: $SOLR_ADMIN_PASSWORD
  - name: SOLR_URL
    value: http://admin:$SOLR_ADMIN_PASSWORD@solr.default.svc.cluster.local:8983/solr/
  - name: SECRET_KEY_BASE
    value: $SECRET_KEY_BASE
  - name: SENTRY_DSN
    value: https://bcbcbdd237984028a7d0b76d96ba90dd@o1008683.ingest.sentry.io/6745017
  - name: OMP_THREAD_LIMIT
    value: "1"

worker:
  replicaCount: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
  extraVolumeMounts: *volMounts
  extraEnvVars: *envVars
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 101
    fsGroup: 101
    fsGroupChangePolicy: "OnRootMismatch"
podSecurityContext:
  runAsUser: 1001
  runAsGroup: 101
  fsGroup: 101
  fsGroupChangePolicy: "OnRootMismatch"

embargoRelease:
  enabled: false
leaseRelease:
  enabled: false

redis:
  cluster:
    enabled: true
  password: production

imagePullSecrets:
  - name: github-registry

solr:
  enabled: false
  replicaCount: 2
  collectionReplicas: 1
  zookeeper:
    replicaCount: 1

fcrepo:
  enabled: false
  storage:
    size: 105Gi

postgresql:
  enabled: false

externalSolrHost: solr.default.svc.cluster.local
externalSolrUser: admin
externalSolrPassword: $SOLR_ADMIN_PASSWORD
externalSolrCollection: "hyku"
externalFcrepoHost: fcrepo.fcrepo.svc.cluster.local
externalPostgresql:
  username: postgres
  password: $DATABASE_PASSWORD
  database: hyku
  host: postgresql.default.svc.cluster.local
global:
  hyraxName: hyku-production-hyrax

nginx:
  enabled: true
  image:
    registry: registry.gitlab.com
    repository: notch8/scripts/bitnami-nginx
    tag: 1.21.5-debian-10-r4
  serverBlock: |-
    upstream rails_app {
      server {{ .Values.global.hyraxName }};
    }

    map ${DOLLAR}status ${DOLLAR}loggable {
        ~^444  0;
        default 1;
    }

    log_format loki 'host=${DOLLAR}host ip=${DOLLAR}http_x_forwarded_for remote_user=${DOLLAR}remote_user [${DOLLAR}time_local] '
                      'request="${DOLLAR}request" status=${DOLLAR}status bytes=${DOLLAR}body_bytes_sent '
                      'referer="${DOLLAR}http_referer" agent="${DOLLAR}http_user_agent" request_time=${DOLLAR}request_time upstream_response_time=${DOLLAR}upstream_response_time upstream_response_length=${DOLLAR}upstream_response_length';

    error_log  /opt/bitnami/nginx/logs/error.log warn;
    #tcp_nopush     on;

    # Cloudflare ips see for refresh
    # https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs-logging-visitor-IP-addresses
    # update list https://www.cloudflare.com/ips/
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/13;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2a06:98c0::/29;
    set_real_ip_from 2c0f:f248::/32;

    real_ip_header X-Forwarded-For;
    real_ip_recursive on;
    include /opt/bitnami/nginx/conf/conf.d/*.conf;
    server {
        listen 8080;
        server_name _;
        root /app/samvera/hyrax-webapp/public;
        index index.html;

        client_body_in_file_only clean;
        client_body_buffer_size 32K;
        client_max_body_size 0;
        access_log /opt/bitnami/nginx/logs/access.log loki;
        # if=${DOLLAR}loggable;

        sendfile on;
        send_timeout 300s;

        include /opt/bitnami/nginx/conf/bots.d/ddos.conf;
        include /opt/bitnami/nginx/conf/bots.d/blockbots.conf;

        location ~ (\.php|\.aspx|\.asp) {
        	return 404;
        }

        # deny requests for files that should never be accessed
        location ~ /\. {
          deny all;
        }

        location ~* ^.+\.(rb|log)${DOLLAR} {
          deny all;
        }

        # serve static (compiled) assets directly if they exist (for rails production)
        location ~ ^/(assets|packs|fonts|images|javascripts|stylesheets|swfs|system)/ {
          try_files ${DOLLAR}uri @rails;

          # access_log off;
          gzip_static on; # to serve pre-gzipped version

          expires max;
          add_header Cache-Control public;

          # Some browsers still send conditional-GET requests if there's a
          # Last-Modified header or an ETag header even if they haven't
          # reached the expiry date sent in the Expires header.
          add_header Last-Modified "";
          add_header ETag "";
          break;
        }

        # send non-static file requests to the app server
        location / {
          try_files ${DOLLAR}uri @rails;
        }

        location @rails {
          proxy_set_header  X-Real-IP  ${DOLLAR}remote_addr;
          proxy_set_header  X-Forwarded-For ${DOLLAR}proxy_add_x_forwarded_for;
          proxy_set_header Host ${DOLLAR}http_host;
          proxy_redirect off;
          proxy_pass http://rails_app;
        }
    }
